--DEBEMOS DARLE PERMISO AL USUARIO SYSTEM PARA QUE EJECUTE SENTENCIAS TIPO SCRIPT:
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;
--Crear un usuario:
CREATE USER musicpro IDENTIFIED BY musicpro;
--Dar permisos al usuario:
GRANT CONNECT, RESOURCE, DBA TO musicpro;